apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hpgrahsl-poi-gateway-app-dev
  annotations:
    argocd/app-name: hpgrahsl-poi-gateway-app-dev
    backstage.io/kubernetes-id: hpgrahsl-poi-gateway-app
    backstage.io/kubernetes-namespace: hpgrahsl
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-aro24/hpgrahsl-gateway
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.kovj5vhc.eastus.aroapp.io/dev-pipelines/ns/hpgrahsl/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.kovj5vhc.eastus.aroapp.io/k8s/ns/hpgrahsl/deployments/hpgrahsl-poi-gateway-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.kovj5vhc.eastus.aroapp.io/#https://github.com/rhdh-aro24/hpgrahsl-gateway?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/hpgrahsl"
  system: workshop-system-hpgrahsl
  providesApis:
    - gateway-api-hpgrahsl
  consumesApis:
    - backend-api-hpgrahsl
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-hpgrahsl
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/hpgrahsl"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: gateway-api-hpgrahsl
  description: API surface exposed to interact with Backends (summit POIs + parks data) via the Gateway
  links:
    - url: http://hpgrahsl-poi-gateway-app-hpgrahsl.apps.kovj5vhc.eastus.aroapp.io/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh-aro24/hpgrahsl-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/hpgrahsl"
  system: workshop-system-hpgrahsl
  definition:
    $text: https://github.com/rhdh-aro24/hpgrahsl-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
